language: node_js
node_js:
- 6
- 8
- 9
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  firefox: latest
deploy:
- provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    node: 9
    tags: true
    repo: ringcentral/ringcentral-js
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - sdk/build/ringcentral.js
  - sdk/build/ringcentral.js.map
  - sdk/build/ringcentral.min.js
  - sdk/build/ringcentral.min.js.map
  - subscriptions/build/ringcentral-subscriptions.js
  - subscriptions/build/ringcentral-subscriptions.js.map
  - subscriptions/build/ringcentral-subscriptions.min.js
  - subscriptions/build/ringcentral-subscriptions.min.js.map
  on:
    node: 9
    tags: true
    repo: ringcentral/ringcentral-js
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm run bootstrap
- npm run build
after_success:
- npm run coveralls