language: node_js

node_js:
- stable

cache:
  directories:
  - $HOME/.npm
  - node_modules

addons:
  firefox: latest

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

before_script:
- DEBUG=eslint:cli-engine npm run lint:all
- npm run build

deploy:
- provider: script
  script: bash npm run publish:canary -- --yes
  skip_cleanup: true
  on:
    branch: master
    tags: false
    repo: ringcentral/ringcentral-js
- provider: script
  script: bash npm run publish:fromgit -- --yes
  skip_cleanup: true
  on:
    tags: true
    repo: ringcentral/ringcentral-js
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - sdk/dist/ringcentral.js
  - sdk/dist/ringcentral.js.map
  - sdk/dist/ringcentral.min.js
  - sdk/dist/ringcentral.min.js.map
  - subscriptions/dist/ringcentral-subscriptions.js
  - subscriptions/dist/ringcentral-subscriptions.js.map
  - subscriptions/dist/ringcentral-subscriptions.min.js
  - subscriptions/dist/ringcentral-subscriptions.min.js.map
  on:
    tags: true
    repo: ringcentral/ringcentral-js

after_success:
- npm run test:coverage